"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const CarritoDeCompras_controllers_1 = require("../controllers/CarritoDeCompras.controllers");
const router = (0, express_1.Router)();
router.post("/addCarrito", CarritoDeCompras_controllers_1.createCarritoDeCompras);
router.get("/carritos", CarritoDeCompras_controllers_1.getCarritosDeCompras);
router.get("/carrito/:Id_Carrito", CarritoDeCompras_controllers_1.getCarritoDeComprasById);
router.put("/carrito/:Id_Carrito", CarritoDeCompras_controllers_1.updateCarritoDeCompras);
router.delete("/carrito/:Id_Carrito", CarritoDeCompras_controllers_1.deleteCarritoDeCompras);
exports.default = router;
