"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const Complemento_controllers_1 = require("../controllers/Complemento.controllers");
const verifyToken_1 = require("../middleware/verifyToken");
const Celular_controllers_1 = require("../controllers/Celular.controllers");
const router = (0, express_1.Router)();
router.use(verifyToken_1.authMiddleware);
router.get("/Complemento", Complemento_controllers_1.getComplemento);
router.get("/getDocumento", Complemento_controllers_1.getDocumento);
router.get("/getCelular", Celular_controllers_1.getCelular);
exports.default = router;
