"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const Compra_controllers_1 = require("../controllers/Compra.controllers");
const GastoGeneral_controllers_1 = require("../controllers/GastoGeneral.controllers");
const verifyToken_1 = require("../middleware/verifyToken");
const router = (0, express_1.Router)();
router.use(verifyToken_1.authMiddleware);
router.post("/registrarCompra", Compra_controllers_1.registrarCompra);
router.get("/getCompras", Compra_controllers_1.getCompras);
router.get("/getCompra/:id", Compra_controllers_1.getCompra);
router.put("/actualizarCompra/:id", Compra_controllers_1.updateCompra);
router.delete("/anularCompra/:id", Compra_controllers_1.anularCompra);
router.post("/registrarGastoGeneral", GastoGeneral_controllers_1.registrarGastoGeneral);
router.get("/getGastosGenerales", GastoGeneral_controllers_1.getGastosGenerales);
router.get("/getGastoGeneral/:id", GastoGeneral_controllers_1.getGastoGeneral);
router.put("/actualizarGastoGeneral/:id", GastoGeneral_controllers_1.updateGastoGeneral);
router.delete("/anularGastoGeneral/:id", GastoGeneral_controllers_1.anularGastoGeneral);
exports.default = router;
