"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const DetalleVenta_controllers_1 = require("../controllers/DetalleVenta.controllers");
const router = (0, express_1.Router)();
router.post("/addDetalleVenta", DetalleVenta_controllers_1.createDetalleVenta);
router.get("/detallesVenta", DetalleVenta_controllers_1.getDetallesVenta);
router.get("/detallesVenta/:Venta_Id", DetalleVenta_controllers_1.getDetallesVentaByVentaId);
router.put("/detallesVenta/:Venta_Id/:Producto_Id", DetalleVenta_controllers_1.updateDetalleVenta);
router.delete("/detallesVenta/:Venta_Id/:Producto_Id", DetalleVenta_controllers_1.deleteDetalleVenta);
router.get("/detalle-venta/:Venta_Id", DetalleVenta_controllers_1.getProductosPorVenta);
exports.default = router;
