"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const Distribucion_controllers_1 = require("../controllers/Distribucion.controllers");
const verifyToken_1 = require("../middleware/verifyToken");
const router = (0, express_1.Router)();
router.use(verifyToken_1.authMiddleware);
router.get("/distribuciones", Distribucion_controllers_1.getDistribuciones);
router.get("/getDistribucionesSucursal", Distribucion_controllers_1.getDistribucionesSucursal);
router.get("/ObtenerCLienteDestino/:id", Distribucion_controllers_1.ObtenerCLienteDestino);
router.post("/distribucion", Distribucion_controllers_1.createDistribucion);
router.get("/distribucion/:id", Distribucion_controllers_1.getDistribucion);
router.put("/distribucion/:id", Distribucion_controllers_1.updateDistribucion);
router.put("/distribucionanular/:id", Distribucion_controllers_1.anularDistribucion);
router.delete("/distribucion/:id", Distribucion_controllers_1.deleteDistribucion);
exports.default = router;
