"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const Empleado_controllers_1 = require("../controllers/Empleado.controllers");
const verifyToken_1 = require("../middleware/verifyToken");
const Cargo_controllers_1 = require("../controllers/Cargo.controllers");
const router = (0, express_1.Router)();
router.get('/getCargo', verifyToken_1.authMiddleware, Cargo_controllers_1.getCargo);
router.post("/AddEmpleado", verifyToken_1.authMiddleware, Empleado_controllers_1.CreateEmpleado);
router.put('/UpdateEmpleado/:id', verifyToken_1.authMiddleware, Empleado_controllers_1.UpdateEmpleado);
router.delete('/deleteEmpleado/:id', verifyToken_1.authMiddleware, Empleado_controllers_1.deleteEmpleado);
router.get('/getEmpleados/:id', verifyToken_1.authMiddleware, Empleado_controllers_1.getEmpleados);
router.get('/getEmpleadosVendedores', verifyToken_1.authMiddleware, Empleado_controllers_1.getEmpleadosVendedores);
exports.default = router;
