"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const Ingredientes_controllers_1 = require("../controllers/Ingredientes.controllers");
const verifyToken_1 = require("../middleware/verifyToken");
const router = (0, express_1.Router)();
router.use(verifyToken_1.authMiddleware);
router.get('/getProductoIngrediente/:id', Ingredientes_controllers_1.getProductoIngrediente);
router.post('/registrarProduccionDeProducto', Ingredientes_controllers_1.registrarProduccionDeProducto);
router.put('/actualizarIngredienteReceta/:id', Ingredientes_controllers_1.actualizarIngredienteReceta);
router.delete('/eliminarIngredienteReceta/:id', Ingredientes_controllers_1.eliminarIngredienteReceta);
exports.default = router;
