"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const Pago_controllers_1 = require("../controllers/Pago.controllers");
const verifyToken_1 = require("../middleware/verifyToken");
const router = (0, express_1.Router)();
router.use(verifyToken_1.authMiddleware);
router.get('/getpago', Pago_controllers_1.getPagos);
router.get('/getpagoVenta/:id', Pago_controllers_1.getPagosVenta);
exports.default = router;
