"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const PedidoProducto_controllers_1 = require("../controllers/PedidoProducto.controllers");
const router = (0, express_1.Router)();
router.post("/addPedidoProducto", PedidoProducto_controllers_1.addPedidoProducto);
router.get("/pedidoProductos", PedidoProducto_controllers_1.getPedidoProductos);
router.get("/pedidoProductos/:Id_Pedido/:Id_Producto", PedidoProducto_controllers_1.getPedidoProductoById);
router.put("/pedidoProductos/:Id_Pedido/:Id_Producto", PedidoProducto_controllers_1.updatePedidoProducto);
router.delete("/pedidoProductos/:Id_Pedido/:Id_Producto", PedidoProducto_controllers_1.deletePedidoProducto);
exports.default = router;
