"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const verifyToken_1 = require("../middleware/verifyToken");
const Pedido_controllers_1 = require("../controllers/Pedido.controllers");
const TipoPedido_controllers_1 = require("../controllers/TipoPedido.controllers");
const router = (0, express_1.Router)();
router.use(verifyToken_1.authMiddleware);
router.get("/pedidos", Pedido_controllers_1.getPedidos);
router.post("/Addpedidos", Pedido_controllers_1.registrarPedido);
router.post("/AddpedidosRapido", Pedido_controllers_1.registrarPedidoRapido);
router.put("/anularPedido/:id", Pedido_controllers_1.anularpedido);
router.put("/enviarPedido/:id", Pedido_controllers_1.enviarPedido);
router.put("/finalizarPedido/:id", Pedido_controllers_1.finalizarPedido);
router.put("/devolverProducto/:id", Pedido_controllers_1.devolverProductoPedido);
router.put("/actualizarPedido/:id", Pedido_controllers_1.actualizarPedido);
router.get("/getTipopedido", TipoPedido_controllers_1.getTipopedido);
exports.default = router;
