"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const Producto_controllers_1 = require("../controllers/Producto.controllers");
const verifyToken_1 = require("../middleware/verifyToken");
const ProductoMedida_controllers_1 = require("../controllers/ProductoMedida.controllers");
const Ingredientes_controllers_1 = require("../controllers/Ingredientes.controllers");
const router = (0, express_1.Router)();
router.use(verifyToken_1.authMiddleware);
router.get('/productos-vista', Producto_controllers_1.getProductosVista);
router.post("/producto", Producto_controllers_1.createProducto);
router.put('/producto/:id', Producto_controllers_1.updateProducto);
router.post('/updateCreatePrecioProducto', ProductoMedida_controllers_1.updateCreatePrecioProducto);
router.get('/productos', Producto_controllers_1.getProductos);
router.delete('/productos/:id', Producto_controllers_1.deleteProducto);
router.get('/getproducto', Producto_controllers_1.getProducto);
router.get('/getProductomedidas', ProductoMedida_controllers_1.getProductomedidas);
router.get('/getProductoIngrediente/:id', Ingredientes_controllers_1.getProductoIngrediente);
router.get('/getmedidasdelProducto/:id', ProductoMedida_controllers_1.getmedidasdelProducto);
router.get('/getmedidasdelProductoPrecio/:id', ProductoMedida_controllers_1.getmedidasdelProductoPrecio);
exports.default = router;
