"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const VentasReporte_controllers_1 = require("../controllers/reportes/VentasReporte.controllers");
const ProduccionReporte_controllers_1 = require("../controllers/reportes/ProduccionReporte.controllers");
const TransferenciaReporte_controllers_1 = require("../controllers/reportes/TransferenciaReporte.controllers");
const InventarioReporte_controllers_1 = require("../controllers/reportes/InventarioReporte.controllers");
const ComprasReporte_controllers_1 = require("../controllers/reportes/ComprasReporte.controllers");
const EmpleadosReporte_controllers_1 = require("../controllers/reportes/EmpleadosReporte.controllers");
const FinancieroReporte_controllers_1 = require("../controllers/reportes/FinancieroReporte.controllers");
const GastosGeneralesReporte_controllers_1 = require("../controllers/reportes/GastosGeneralesReporte.controllers");
const RevendedorReporte_controllers_1 = require("../controllers/reportes/RevendedorReporte.controllers");
const verifyToken_1 = require("../middleware/verifyToken");
const router = (0, express_1.Router)();
router.use(verifyToken_1.authMiddleware);
// --- REPORTES EXISTENTES/REFACTORIZADOS ---
router.get("/reporte/ventas-detallado", VentasReporte_controllers_1.getReporteVentasDetallado);
router.get("/reporte/pedidos-detallado", VentasReporte_controllers_1.getReportePedidosDetallado);
router.get("/reporte/produccion-detallado", ProduccionReporte_controllers_1.getReporteProduccionDetallado);
router.get("/reporte/transferencias-detallado", TransferenciaReporte_controllers_1.getReporteTransferenciasDetallado);
router.get("/reporte/revendedor-detallado", RevendedorReporte_controllers_1.getReporteRevendedorDetallado);
// --- NUEVOS REPORTES CONSOLIDADOS (prompreporte.txt) ---
router.get("/reporte/ventas-consolidado", VentasReporte_controllers_1.getReporteVentasConsolidado);
router.get("/reporte/pedidos-consolidado", VentasReporte_controllers_1.getReportePedidosConsolidado);
router.get("/reporte/produccion-consolidado", ProduccionReporte_controllers_1.getReporteProduccionConsolidado);
router.get("/reporte/transferencias-consolidado", TransferenciaReporte_controllers_1.getReporteTransferenciasConsolidado);
router.get("/reporte/inventario-consolidado", InventarioReporte_controllers_1.getReporteInventarioConsolidado);
router.get("/reporte/kardex", InventarioReporte_controllers_1.getReporteKardex);
router.get("/reporte/compras-consolidado", ComprasReporte_controllers_1.getReporteComprasConsolidado);
router.get("/reporte/precios-historico", ComprasReporte_controllers_1.getReportePreciosHistorico);
router.get("/reporte/empleados-operativo", EmpleadosReporte_controllers_1.getReporteEmpleadosOperativo);
router.get("/reporte/vendedores-liquidacion", EmpleadosReporte_controllers_1.getReporteVendedoresLiquidacion);
router.get("/reporte/financiero-consolidado", FinancieroReporte_controllers_1.getReporteFinancieroConsolidado);
router.get("/reporte/revendedor-consolidado", RevendedorReporte_controllers_1.getReporteRevendedorConsolidado);
router.get("/reporte/gastos-generales", GastosGeneralesReporte_controllers_1.getReporteGastosGenerales);
exports.default = router;
