"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const Rol_controllers_1 = require("../controllers/Rol.controllers");
const verifyToken_1 = require("../middleware/verifyToken");
const router = (0, express_1.Router)();
router.use(verifyToken_1.authMiddleware);
router.post('/addRole', Rol_controllers_1.createRole);
router.get('/filroles', Rol_controllers_1.filRoles);
router.get('/role/:id', Rol_controllers_1.getRole);
router.get('/role', Rol_controllers_1.getRoles);
router.get('/permiso', Rol_controllers_1.getPermiso);
router.get('/permisos/:idMenu', Rol_controllers_1.getPermisosPorMenu);
router.put('/role/:id', Rol_controllers_1.updateRole);
router.delete('/role/:id', Rol_controllers_1.deleteRole);
router.get('/rolemenus/:id', Rol_controllers_1.getobtenerMenus);
exports.default = router;
