"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const verifyToken_1 = require("../middleware/verifyToken");
const RolUsuario_controllers_1 = require("../controllers/RolUsuario.controllers");
const router = (0, express_1.Router)();
router.use(verifyToken_1.authMiddleware);
router.post('/AsignarRolUsuario', RolUsuario_controllers_1.AsignarRol);
router.delete('/DeleteRolUsuario/:idu/:idr', RolUsuario_controllers_1.DeleteRol);
router.put('/Rolusuario/:id', RolUsuario_controllers_1.AsignarupdateRol);
exports.default = router;
