"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const Sucursal_controllers_1 = require("../controllers/Sucursal.controllers");
const verifyToken_1 = require("../middleware/verifyToken");
const Horno_controllers_1 = require("../controllers/Horno.controllers");
const router = (0, express_1.Router)();
router.use(verifyToken_1.authMiddleware);
router.get("/gethornos/:id", Horno_controllers_1.getHornos);
router.put("/UpdateORPostHorno", Horno_controllers_1.UpdateORPostHorno);
router.post("/CreateGastos", Sucursal_controllers_1.CreateGastos);
router.get('/ListGasto', Sucursal_controllers_1.ListGasto);
router.post("/Sucursal", Sucursal_controllers_1.createSucursal);
router.get("/Sucursales", Sucursal_controllers_1.getSucursales);
router.get("/BuscarSucursal/:id", Sucursal_controllers_1.getSucursalById);
router.get("/getSucursalDireccion/:id", Sucursal_controllers_1.getSucursalDireccion);
router.put("/UpdSucursal/:id", Sucursal_controllers_1.updateSucursal);
router.delete("/DelSucursal/:id", Sucursal_controllers_1.deleteSucursal);
router.get('/Listsucursal', Sucursal_controllers_1.Listsucursal);
exports.default = router;
