"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const UsuarioSucursal_controllers_1 = require("../controllers/UsuarioSucursal.controllers");
const router = (0, express_1.Router)();
router.post('/usuario-sucursal', UsuarioSucursal_controllers_1.createUsuarioSucursal);
router.get('/usuario-sucursal', UsuarioSucursal_controllers_1.getUsuarioSucursales);
router.get('/usuario-sucursal/sucursal/:id', UsuarioSucursal_controllers_1.getUsuarioSucursalesBySucursal);
router.get('/usuario-sucursal/usuario/:id', UsuarioSucursal_controllers_1.getUsuarioSucursalesByUsuario);
router.delete('/usuario-sucursal/:id', UsuarioSucursal_controllers_1.deleteUsuarioSucursal);
router.get('/usuario-sucursal/products-by-user/:id', UsuarioSucursal_controllers_1.getProductsByUserId);
exports.default = router;
