"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const Venta_controllers_1 = require("../controllers/Venta.controllers");
const verifyToken_1 = require("../middleware/verifyToken");
const router = (0, express_1.Router)();
router.use(verifyToken_1.authMiddleware);
router.post('/ventas', Venta_controllers_1.registrarVenta);
router.get('/ventas', Venta_controllers_1.getVentas);
router.get('/ventasSucursal', Venta_controllers_1.getVentasSucursal);
router.put('/Anularventas/:id', Venta_controllers_1.anularVenta);
router.put('/ventas/:id', Venta_controllers_1.actualizarVenta);
exports.default = router;
